// <auto-generated />
namespace BlogApp.Repo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PostIdIssue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostIdIssue));
        
        string IMigrationMetadata.Id
        {
            get { return "201806091716250_PostIdIssue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
